/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dictionary.h"

bool_t
xdr_strlist (XDR *xdrs, strlist *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->str, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dict (XDR *xdrs, dict *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->word, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->wlen))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->meaning, 20,
		sizeof (strlist), (xdrproc_t) xdr_strlist))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->d, 100,
		sizeof (dict), (xdrproc_t) xdr_dict))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}
