/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "dictionary.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
dict_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		dict insert_dict_prog_1_arg;
		dict duplicate_dict_prog_1_arg;
		dict get_meaning_dict_prog_1_arg;
		dict delete_word_dict_prog_1_arg;
		dict add_mean_dict_prog_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INSERT_DICT_PROG:
		_xdr_argument = (xdrproc_t) xdr_dict;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) insert_dict_prog_1_svc;
		break;

	case DISPLAY_DICT_PROG:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_data;
		local = (char *(*)(char *, struct svc_req *)) display_dict_prog_1_svc;
		break;

	case DUPLICATE_DICT_PROG:
		_xdr_argument = (xdrproc_t) xdr_dict;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) duplicate_dict_prog_1_svc;
		break;

	case GET_MEANING_DICT_PROG:
		_xdr_argument = (xdrproc_t) xdr_dict;
		_xdr_result = (xdrproc_t) xdr_dict;
		local = (char *(*)(char *, struct svc_req *)) get_meaning_dict_prog_1_svc;
		break;

	case DELETE_WORD_DICT_PROG:
		_xdr_argument = (xdrproc_t) xdr_dict;
		_xdr_result = (xdrproc_t) xdr_dict;
		local = (char *(*)(char *, struct svc_req *)) delete_word_dict_prog_1_svc;
		break;

	case ADD_MEAN_DICT_PROG:
		_xdr_argument = (xdrproc_t) xdr_dict;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_mean_dict_prog_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DICT_PROG, DICT_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DICT_PROG, DICT_VERS, dict_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DICT_PROG, DICT_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DICT_PROG, DICT_VERS, dict_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DICT_PROG, DICT_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
